/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

/**
 *
 * @author guima
 */
public class PainelFiltrosViagemMarte extends javax.swing.JPanel {

    public PainelFiltrosViagemMarte() {
        initComponents();
    }
    public char isLembrança(){
        char albúm = 'X';
        if(LembrançaMartebuttonGroup.getSelection() != null){
            switch(LembrançaMartebuttonGroup.getSelection().getMnemonic()){
                case 0: albúm = 'T';break;
                case 1: albúm = 'F';
            }
        }
        System.out.println("album: " + albúm);
        return albúm;
    }
    public void limparFiltros(){
        LembrançaMartebuttonGroup.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LembrançaMartebuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        simRadioButton = new javax.swing.JRadioButton();
        nãoRadioButton = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lembrança de Marte"));

        LembrançaMartebuttonGroup.add(simRadioButton);
        simRadioButton.setText("Sim");
        jPanel1.add(simRadioButton);

        LembrançaMartebuttonGroup.add(nãoRadioButton);
        nãoRadioButton.setMnemonic(1);
        nãoRadioButton.setText("Não");
        jPanel1.add(nãoRadioButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup LembrançaMartebuttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nãoRadioButton;
    private javax.swing.JRadioButton simRadioButton;
    // End of variables declaration//GEN-END:variables
}
