/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;
import entidade.EstaçãoLunar.OrbitaLua;
/**
 *
 * @author guima
 */
public class PainelFiltrosEstaçãoLunar extends javax.swing.JPanel {

    /**
     * Creates new form PainelFiltrosEstaçãoLunar
     */
    public PainelFiltrosEstaçãoLunar() {
        initComponents();
    }
    public OrbitaLua getSelectedOrbitaLua(){
        OrbitaLua orbita = null;    
        if(orbitabuttonGroup.getSelection() != null){
            orbita = OrbitaLua.values()[orbitabuttonGroup.getSelection().getMnemonic()];     
        }
        return orbita;
    }
    public void LimparFiltros(){
        orbitabuttonGroup.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orbitabuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        perigeuradioButton = new javax.swing.JRadioButton();
        apogeuRadioButton = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(350, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Órbita da Lua"));

        orbitabuttonGroup.add(perigeuradioButton);
        perigeuradioButton.setText("Perigeu");
        perigeuradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perigeuradioButtonActionPerformed(evt);
            }
        });

        orbitabuttonGroup.add(apogeuRadioButton);
        apogeuRadioButton.setMnemonic('\u0001');
        apogeuRadioButton.setText("Apogeu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perigeuradioButton)
                .addGap(32, 32, 32)
                .addComponent(apogeuRadioButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perigeuradioButton)
                    .addComponent(apogeuRadioButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void perigeuradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perigeuradioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perigeuradioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton apogeuRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup orbitabuttonGroup;
    private javax.swing.JRadioButton perigeuradioButton;
    // End of variables declaration//GEN-END:variables
}
